### ISSUE TITLE
can not run demo

### ISSUE THREAD

**Issue by Thanh-Binh** [evegard/grid-place-cell-nav#1]
Hi
I try to run a demo in my Ubuntu 22.04 LTS, and have got errors (see below).
Could you please help me?
How can I run it without python? I mean:
./build/clutteredNavi --modules=12 --agent=combined --live-plot

Thanks
################################
 ./convert.py environments/replay_demo.txt | ./build/clutteredNavi --modules=12 --agent=combined --live-plot
Module count: 12
Agent type: combined
Place field radius: 7
/usr/bin/env: ‘python’: No such file or directory
Traceback (most recent call last):
  File "/home/binh/experiments/HTMs/ClutteredEnvNavi/./convert.py", line 211, in <module>
    Converter(args).process_script()
  File "/home/binh/experiments/HTMs/ClutteredEnvNavi/./convert.py", line 173, in process_script
    self.load_svg(svg_filename, svg_scale)
  File "/home/binh/experiments/HTMs/ClutteredEnvNavi/./convert.py", line 52, in load_svg
    processed_svg_root = xml.etree.ElementTree.fromstring(flatten_output[0])
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1343, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by evegard** [comment]
Hi, thanks for your interest in this work. :-)

I believe this error might happen because the `convert.py` script depends on an Inkscape extension to preprocess the SVG files. See [line 43](https://github.com/evegard/grid-place-cell-nav/blob/main/convert.py#L43) in `convert.py` -- it calls `/usr/share/inkscape/extensions/flatten.py` to flatten the paths in the SVG file before continuing. If you try to run the extension script directly e.g. like `/usr/share/inkscape/extensions/flatten.py --help`, I suspect you will get an error message identical to the first error in your log above (`/usr/bin/env: ‘python’: No such file or directory`). The rest of your error log is simply that the `convert.py` script doesn't deal well with the Inkscape extension crashing like that.

This might be because Inkscape extensions in Ubuntu 22.04 assume there is a Python interpreter available via the command `python`. Python 2/3 is nowadays supposed to be called using `python2` or `python3` respectively, not simply "`python`". However, there is a helper package available in Ubuntu to alias the `python` command into `python3`, that hopefully might work.

Could you try the following command to install that package and see if that fixes the issue?

```
sudo apt install python-is-python3
```

**Comment by Thanh-Binh** [comment]
thanks for your reply.
I have just fixed that problem and can run convert.py separately.
I use python 3.10, Ubuntu 22.04LTS

But have no success by running
./convert.py environments/deflect_demo.txt | ./build/clutteredNavi --modules=12 --agent=combined --live-plot

I have the following errors (see belows).

Moreover I want to understand how Grid cells and place cells work.
Could you pls recommend me which network or components of Agent is interesting to consider?
Thanks

```C
./show_plot.py 
Rendering plots from './plot_pipe'
Main thread: Starting Tk
Main thread: Creating initial widget
Main thread: Creating plot queue and show queue
Main thread: Creating internal pipe
Main thread: Setting up internal pipe callback
Main thread: Spawning pipe thread
Pipe thread: Entering infinite loop
Main thread: Spawning plot thread
Pipe thread: Opening pipe
Plot thread: Entering infinite loop
Plot thread: Waiting for data from plot queue
Main thread: Entering main loop
Pipe thread: Entering read loop
Plot thread: Checking number of waiting items
0 Plot thread: Possibly writing source file
Plot thread: Opening gnuplot
Plot thread: Writing to gnuplot and reading output
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/binh/experiments/HTMs/ClutteredEnvNavi/./show_plot.py", line 117, in run
    (image_data, _) = gnuplot_process.communicate(plot_data)
  File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1983, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
Pipe thread: Got EOF, closing pipe
Pipe thread: Opening pipe
Pipe thread: Entering read loop
Pipe thread: Got EOF, closing pipe
Pipe thread: Opening pipe
Pipe thread: Entering read loop
Pipe thread: Got EOF, closing pipe
Pipe thread: Opening pipe
Pipe thread: Entering read loop
Pipe thread: Got EOF, closing pipe
Pipe thread: Opening pipe
Pipe thread: Entering read loop
Pipe thread: Got EOF, closing pipe
```
